---
abstract: 'Perl bindings to the Git linkable library (libgit2)'
author:
  - 'Jacques Germishuys <jacquesg@cpan.org>'
  - 'Alessandro Ghedini <alexbio@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Cwd: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Path: '0'
  File::Slurp::Tiny: '0.001'
  File::Spec: '0'
  File::Spec::Functions: '0'
  File::Spec::Unix: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  Test::Pod: '0.0'
  Test::Pod::Coverage: '0.0'
  Time::Local: '0'
  perl: '5.006'
configure_requires:
  Devel::CheckLib: '0.6'
  ExtUtils::Constant: '0.23'
  ExtUtils::MakeMaker: 6.63_03
  ExtUtils::PkgConfig: '0'
  File::Basename: '2.74'
  Getopt::Long: '2.35'
  perl: '5.004'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-Raw
provides:
  Git::Raw:
    file: lib/Git/Raw.pm
    version: '0.80'
  Git::Raw::AnnotatedCommit:
    file: lib/Git/Raw/AnnotatedCommit.pm
    version: '0.80'
  Git::Raw::Blame:
    file: lib/Git/Raw/Blame.pm
    version: '0.80'
  Git::Raw::Blame::Hunk:
    file: lib/Git/Raw/Blame/Hunk.pm
    version: '0.80'
  Git::Raw::Blob:
    file: lib/Git/Raw/Blob.pm
    version: '0.80'
  Git::Raw::Branch:
    file: lib/Git/Raw/Branch.pm
    version: '0.80'
  Git::Raw::Cert:
    file: lib/Git/Raw/Cert.pm
    version: '0.80'
  Git::Raw::Cert::HostKey:
    file: lib/Git/Raw/Cert/HostKey.pm
    version: '0.80'
  Git::Raw::Cert::X509:
    file: lib/Git/Raw/Cert/X509.pm
    version: '0.80'
  Git::Raw::Commit:
    file: lib/Git/Raw/Commit.pm
    version: '0.80'
  Git::Raw::Config:
    file: lib/Git/Raw/Config.pm
    version: '0.80'
  Git::Raw::Cred:
    file: lib/Git/Raw/Cred.pm
    version: '0.80'
  Git::Raw::Diff:
    file: lib/Git/Raw/Diff.pm
    version: '0.80'
  Git::Raw::Diff::Delta:
    file: lib/Git/Raw/Diff/Delta.pm
    version: '0.80'
  Git::Raw::Diff::File:
    file: lib/Git/Raw/Diff/File.pm
    version: '0.80'
  Git::Raw::Diff::Hunk:
    file: lib/Git/Raw/Diff/Hunk.pm
    version: '0.80'
  Git::Raw::Diff::Stats:
    file: lib/Git/Raw/Diff/Stats.pm
    version: '0.80'
  Git::Raw::Error:
    file: lib/Git/Raw/Error.pm
    version: '0.80'
  Git::Raw::Error::Category:
    file: lib/Git/Raw/Error/Category.pm
    version: '0.80'
  Git::Raw::Filter:
    file: lib/Git/Raw/Filter.pm
    version: '0.80'
  Git::Raw::Filter::List:
    file: lib/Git/Raw/Filter/List.pm
    version: '0.80'
  Git::Raw::Filter::Source:
    file: lib/Git/Raw/Filter/Source.pm
    version: '0.80'
  Git::Raw::Graph:
    file: lib/Git/Raw/Graph.pm
    version: '0.80'
  Git::Raw::Index:
    file: lib/Git/Raw/Index.pm
    version: '0.80'
  Git::Raw::Index::Conflict:
    file: lib/Git/Raw/Index/Conflict.pm
    version: '0.80'
  Git::Raw::Index::Entry:
    file: lib/Git/Raw/Index/Entry.pm
    version: '0.80'
  Git::Raw::Indexer:
    file: lib/Git/Raw/Indexer.pm
    version: '0.80'
  Git::Raw::Mempack:
    file: lib/Git/Raw/Mempack.pm
    version: '0.80'
  Git::Raw::Merge::File::Result:
    file: lib/Git/Raw/Merge/File/Result.pm
    version: '0.80'
  Git::Raw::Note:
    file: lib/Git/Raw/Note.pm
    version: '0.80'
  Git::Raw::Object:
    file: lib/Git/Raw/Object.pm
    version: '0.80'
  Git::Raw::Odb:
    file: lib/Git/Raw/Odb.pm
    version: '0.80'
  Git::Raw::Odb::Backend:
    file: lib/Git/Raw/Odb/Backend.pm
    version: '0.80'
  Git::Raw::Odb::Backend::Loose:
    file: lib/Git/Raw/Odb/Backend/Loose.pm
    version: '0.80'
  Git::Raw::Odb::Backend::OnePack:
    file: lib/Git/Raw/Odb/Backend/OnePack.pm
    version: '0.80'
  Git::Raw::Odb::Backend::Pack:
    file: lib/Git/Raw/Odb/Backend/Pack.pm
    version: '0.80'
  Git::Raw::Odb::Object:
    file: lib/Git/Raw/Odb/Object.pm
    version: '0.80'
  Git::Raw::Packbuilder:
    file: lib/Git/Raw/Packbuilder.pm
    version: '0.80'
  Git::Raw::Patch:
    file: lib/Git/Raw/Patch.pm
    version: '0.80'
  Git::Raw::PathSpec:
    file: lib/Git/Raw/PathSpec.pm
    version: '0.80'
  Git::Raw::PathSpec::MatchList:
    file: lib/Git/Raw/PathSpec/MatchList.pm
    version: '0.80'
  Git::Raw::Rebase:
    file: lib/Git/Raw/Rebase.pm
    version: '0.80'
  Git::Raw::Rebase::Operation:
    file: lib/Git/Raw/Rebase/Operation.pm
    version: '0.80'
  Git::Raw::RefSpec:
    file: lib/Git/Raw/RefSpec.pm
    version: '0.80'
  Git::Raw::Reference:
    file: lib/Git/Raw/Reference.pm
    version: '0.80'
  Git::Raw::Reflog:
    file: lib/Git/Raw/Reflog.pm
    version: '0.80'
  Git::Raw::Reflog::Entry:
    file: lib/Git/Raw/Reflog/Entry.pm
    version: '0.80'
  Git::Raw::Remote:
    file: lib/Git/Raw/Remote.pm
    version: '0.80'
  Git::Raw::Repository:
    file: lib/Git/Raw/Repository.pm
    version: '0.80'
  Git::Raw::Signature:
    file: lib/Git/Raw/Signature.pm
    version: '0.80'
  Git::Raw::Stash:
    file: lib/Git/Raw/Stash.pm
    version: '0.80'
  Git::Raw::Stash::Progress:
    file: lib/Git/Raw/Stash/Progress.pm
    version: '0.80'
  Git::Raw::Tag:
    file: lib/Git/Raw/Tag.pm
    version: '0.80'
  Git::Raw::TransferProgress:
    file: lib/Git/Raw/TransferProgress.pm
    version: '0.80'
  Git::Raw::Tree:
    file: lib/Git/Raw/Tree.pm
    version: '0.80'
  Git::Raw::Tree::Builder:
    file: lib/Git/Raw/Tree/Builder.pm
    version: '0.80'
  Git::Raw::Tree::Entry:
    file: lib/Git/Raw/Tree/Entry.pm
    version: '0.80'
  Git::Raw::Walker:
    file: lib/Git/Raw/Walker.pm
    version: '0.80'
  Git::Raw::Worktree:
    file: lib/Git/Raw/Worktree.pm
    version: '0.80'
requires:
  Carp: '0'
  XSLoader: '0'
  overload: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jacquesg/p5-Git-Raw/issues
  homepage: http://metacpan.org/release/Git-Raw/
  repository: git://github.com/jacquesg/p5-Git-Raw.git
version: '0.80'
x_Dist_Zilla:
  perl:
    version: '5.026001'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename: []
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 0
          prefix: ''
          prune_directory: []
          root: .
      name: '@Author::ALEXBIO/GatherDir'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::ALEXBIO/PruneCruft'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::ALEXBIO/ManifestSkip'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::ALEXBIO/MetaYAML'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::ALEXBIO/License'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::ALEXBIO/Readme'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::ALEXBIO/ExtraTests'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::ALEXBIO/ExecDir'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::ALEXBIO/ShareDir'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::ALEXBIO/Manifest'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::ALEXBIO/TestRelease'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::ALEXBIO/ConfirmRelease'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@Author::ALEXBIO/@GitHub/GitHub::Meta'
      version: '0.44'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      config:
        Dist::Zilla::Plugin::GitHub::Update:
          metacpan: 1
      name: '@Author::ALEXBIO/@GitHub/GitHub::Update'
      version: '0.44'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      config:
        Dist::Zilla::Plugin::Git::NextVersion:
          first_version: 0.01
          version_by_branch: 0
          version_regexp: (?^:^v(.+)$)
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.16.2
          repo_root: .
      name: '@Author::ALEXBIO/Git::NextVersion'
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::ALEXBIO/MetaConfig'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::ALEXBIO/MetaJSON'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::ALEXBIO/AutoPrereqs'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::PodVersion
      name: '@Author::ALEXBIO/PodVersion'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::ALEXBIO/PkgVersion'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::ALEXBIO/NextRelease'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: 0
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: 0
          phase: test
          script_finder:
            - ':PerlExecFiles'
          skips: []
          switch: []
      name: '@Author::ALEXBIO/Test::Compile'
      version: '2.058'
    -
      class: Dist::Zilla::Plugin::Test::CheckManifest
      name: '@Author::ALEXBIO/Test::CheckManifest'
      version: '0.04'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::ALEXBIO/PodSyntaxTests'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::ALEXBIO/PodCoverageTests'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.16.2
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::ALEXBIO/Git::Commit'
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: v0.80
          tag_format: v%v
          tag_message: '%N %v'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.16.2
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::ALEXBIO/Git::Tag'
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.16.2
          repo_root: .
      name: '@Author::ALEXBIO/Git::Push'
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::ALEXBIO/UploadToCPAN'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@Author::ALEXBIO/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Clean
      name: '@Author::ALEXBIO/Clean'
      version: '0.07'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: configure
          type: requires
      name: ConfigureRequires
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
              version: '6.011'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000033'
          version: '0.004'
      name: MetaProvides::Package
      version: '2.004003'
    -
      class: Dist::Zilla::Plugin::MakeMaker::Awesome
      config:
        Dist::Zilla::Plugin::MakeMaker:
          make_path: make
          version: '6.011'
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
          version: '6.011'
      name: MakeMaker::Awesome
      version: '0.41'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: PruneFiles
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/%b
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: ~
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          git_version: 2.16.2
          repo_root: .
      name: Git::CommitBuild
      version: '2.043'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.011'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
      version: '6.011'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.011'
x_serialization_backend: 'YAML::Tiny version 1.73'
